fetch("https://apip.ecoledirecte.com/v3/classes/142/eleves.awp?verbe=get&idCours=156706&v=4.89.3", {
  "headers": {
    "accept": "application/json, text/plain, */*",
    "accept-language": "fr-FR,fr;q=0.9",
    "content-type": "application/x-www-form-urlencoded",
    "priority": "u=1, i",
    "sec-ch-ua": "\"Chromium\";v=\"142\", \"Brave\";v=\"142\", \"Not_A Brand\";v=\"99\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-site",
    "sec-gpc": "1",
    "x-token": "5f5955ab-6be9-4598-a9da-9ba40cd3b106",
    "Referer": "https://www.ecoledirecte.com/"
  },
  "body": "data={\n    \"heureDebut\": \"13:00\",\n    \"heureFin\": \"23:59\"\n}",
  "method": "POST"
});

response : 
{
    "code": 200,
    "token": "5f5955ab-6be9-4598-a9da-9ba40cd3b106",
    "host": "HTTP44",
    "data": {
        "eleves": [
            {
                "id": 3151,
                "nom": "ZZZ TEST 01",
                "particule": "",
                "prenom": "A",
                "sexe": "M",
                "classeId": 142,
                "groupeId": 0,
                "classeLibelle": "S.A.C. TEST (Téo LORMONT Projet)",
                "dateEntree": "2025-09-02",
                "dateSortie": "",
                "numeroBadge": "41510",
                "regime": "Externe libre",
                "email": "a01.zzztest@lyceesaintefamille.com",
                "portable": "06.00.00.00.01",
                "photo": "",
                "dateNaissance": "2000-01-01",
                "estEnStage": false,
                "estApprenant": false,
                "dispense": false,
                "finDispense": "",
                "presenceObligatoire": true,
                "absentAvant": false,
                "dispositifs": []
            },
            {
                "id": 3152,
                "nom": "ZZZ TEST 02",
                "particule": "",
                "prenom": "B",
                "sexe": "F",
                "classeId": 142,
                "groupeId": 0,
                "classeLibelle": "S.A.C. TEST (Téo LORMONT Projet)",
                "dateEntree": "2025-09-02",
                "dateSortie": "",
                "numeroBadge": "41520",
                "regime": "Externe libre",
                "email": "b02.zzztest@lyceesaintefamille.com",
                "portable": "06.00.00.00.02",
                "photo": "",
                "dateNaissance": "2000-01-01",
                "estEnStage": false,
                "estApprenant": false,
                "dispense": false,
                "finDispense": "",
                "presenceObligatoire": true,
                "absentAvant": false,
                "dispositifs": []
            },
            {
                "id": 3153,
                "nom": "ZZZ TEST 03",
                "particule": "",
                "prenom": "C",
                "sexe": "M",
                "classeId": 142,
                "groupeId": 0,
                "classeLibelle": "S.A.C. TEST (Téo LORMONT Projet)",
                "dateEntree": "2025-09-02",
                "dateSortie": "",
                "numeroBadge": "41530",
                "regime": "Externe libre",
                "email": "c03.zzztest@lyceesaintefamille.com",
                "portable": "06.00.00.00.03",
                "photo": "",
                "dateNaissance": "2000-01-01",
                "estEnStage": false,
                "estApprenant": false,
                "dispense": false,
                "finDispense": "",
                "presenceObligatoire": true,
                "absentAvant": false,
                "dispositifs": []
            },
            {
                "id": 3154,
                "nom": "ZZZ TEST 04",
                "particule": "",
                "prenom": "D",
                "sexe": "F",
                "classeId": 142,
                "groupeId": 0,
                "classeLibelle": "S.A.C. TEST (Téo LORMONT Projet)",
                "dateEntree": "2025-09-02",
                "dateSortie": "",
                "numeroBadge": "41540",
                "regime": "Externe libre",
                "email": "d04.zzztest@lyceesaintefamille.com",
                "portable": "06.00.00.00.04",
                "photo": "",
                "dateNaissance": "2000-01-01",
                "estEnStage": false,
                "estApprenant": false,
                "dispense": false,
                "finDispense": "",
                "presenceObligatoire": true,
                "absentAvant": false,
                "dispositifs": []
            },
            {
                "id": 3155,
                "nom": "ZZZ TEST 05",
                "particule": "",
                "prenom": "E",
                "sexe": "M",
                "classeId": 142,
                "groupeId": 0,
                "classeLibelle": "S.A.C. TEST (Téo LORMONT Projet)",
                "dateEntree": "2025-09-02",
                "dateSortie": "",
                "numeroBadge": "41550",
                "regime": "Externe libre",
                "email": "e05.zzztest@lyceesaintefamille.com",
                "portable": "06.00.00.00.05",
                "photo": "",
                "dateNaissance": "2000-01-01",
                "estEnStage": false,
                "estApprenant": false,
                "dispense": false,
                "finDispense": "",
                "presenceObligatoire": true,
                "absentAvant": false,
                "dispositifs": []
            }
        ],
        "entity": {
            "id": 142,
            "code": "SAC-TEST",
            "libelle": "S.A.C. TEST (Téo LORMONT Projet)",
            "type": "C",
            "isFlexible": false,
            "isPrimaire": false
        },
        "appelEnClasse": {
            "effectue": true,
            "dateHeure": "2025-11-21 22:30:11"
        }
    }
}